/**
 * Lightweight rule-based suffix stemmer for grouping vocabulary.
 *
 * NOT a linguistically correct lemmatizer — it's a heuristic that maps
 * morphological variants to a shared key so they cluster together in the
 * vocab browser. False groups (two unrelated words sharing a stem) are
 * harmless: users see the actual words inside each group.
 *
 * Supported: en, es, fr, de, it, pt, nl, sv.
 * Unsupported languages return the word unchanged (flat list, no grouping).
 */

const MIN_STEM = 3; // never strip below this length

/**
 * Suffix rules per language. Ordered longest-first so the greediest
 * match wins. Each entry is [suffix, optional replacement].
 */
const RULES = {
  en: [
    ['fulness', ''],
    ['lessly', ''],
    ['ingness', ''],
    ['isation', ''],
    ['ization', ''],
    ['ating', ''],
    ['ement', ''],
    ['iness', ''],
    ['ments', ''],
    ['tions', ''],
    ['sions', ''],
    ['ness', ''],
    ['ment', ''],
    ['tion', ''],
    ['sion', ''],
    ['able', ''],
    ['ible', ''],
    ['ling', ''],
    ['ting', ''],
    ['ding', ''],
    ['ring', ''],
    ['ning', ''],
    ['ying', ''],
    ['king', ''],
    ['ping', ''],
    ['ful', ''],
    ['ing', ''],
    ['ous', ''],
    ['ive', ''],
    ['ies', 'y'],
    ['ers', ''],
    ['est', ''],
    ['ess', ''],
    ['ely', ''],
    ['led', ''],
    ['ted', ''],
    ['red', ''],
    ['ned', ''],
    ['ped', ''],
    ['ked', ''],
    ['ded', ''],
    ['sed', ''],
    ['ced', ''],
    ['ged', ''],
    ['ved', ''],
    ['bed', ''],
    ['ly', ''],
    ['ed', ''],
    ['er', ''],
    ['es', ''],
    ['al', ''],
    ['en', ''],
    ['s', ''],
  ],
  es: [
    ['aciones', ''],
    ['amente', ''],
    ['imiento', ''],
    ['mente', ''],
    ['ción', ''],
    ['ando', ''],
    ['endo', ''],
    ['ados', ''],
    ['idos', ''],
    ['ador', ''],
    ['adora', ''],
    ['ado', ''],
    ['ido', ''],
    ['aba', ''],
    ['ían', ''],
    ['ara', ''],
    ['ará', ''],
    ['ero', ''],
    ['era', ''],
    ['ar', ''],
    ['er', ''],
    ['ir', ''],
    ['es', ''],
    ['os', ''],
    ['as', ''],
    ['s', ''],
  ],
  fr: [
    ['issement', ''],
    ['ements', ''],
    ['ations', ''],
    ['ement', ''],
    ['ation', ''],
    ['aient', ''],
    ['ment', ''],
    ['tion', ''],
    ['ions', ''],
    ['euse', ''],
    ['ants', ''],
    ['eurs', ''],
    ['ique', ''],
    ['ais', ''],
    ['ait', ''],
    ['ant', ''],
    ['ent', ''],
    ['eur', ''],
    ['ons', ''],
    ['ées', ''],
    ['ion', ''],
    ['er', ''],
    ['ez', ''],
    ['és', ''],
    ['ée', ''],
    ['es', ''],
    ['é', ''],
    ['s', ''],
  ],
  de: [
    ['ungen', ''],
    ['liche', ''],
    ['ische', ''],
    ['heiten', ''],
    ['keiten', ''],
    ['heit', ''],
    ['keit', ''],
    ['lich', ''],
    ['isch', ''],
    ['ung', ''],
    ['ene', ''],
    ['tes', ''],
    ['ten', ''],
    ['est', ''],
    ['ern', ''],
    ['ens', ''],
    ['eln', ''],
    ['en', ''],
    ['er', ''],
    ['te', ''],
    ['em', ''],
    ['es', ''],
    ['el', ''],
    ['e', ''],
    ['s', ''],
  ],
  it: [
    ['amente', ''],
    ['imento', ''],
    ['zione', ''],
    ['zioni', ''],
    ['mente', ''],
    ['ando', ''],
    ['endo', ''],
    ['anti', ''],
    ['enti', ''],
    ['ato', ''],
    ['ito', ''],
    ['ata', ''],
    ['ita', ''],
    ['ati', ''],
    ['iti', ''],
    ['are', ''],
    ['ere', ''],
    ['ire', ''],
    ['ano', ''],
    ['ono', ''],
    ['ava', ''],
    ['iva', ''],
    ['oso', ''],
    ['osa', ''],
    ['one', ''],
    ['oni', ''],
    ['i', ''],
    ['e', ''],
    ['o', ''],
    ['a', ''],
  ],
  pt: [
    ['ações', ''],
    ['mente', ''],
    ['ção', ''],
    ['ando', ''],
    ['endo', ''],
    ['ador', ''],
    ['ados', ''],
    ['idos', ''],
    ['ado', ''],
    ['ido', ''],
    ['oso', ''],
    ['osa', ''],
    ['ar', ''],
    ['er', ''],
    ['ir', ''],
    ['es', ''],
    ['os', ''],
    ['as', ''],
    ['s', ''],
  ],
  nl: [
    ['heden', ''],
    ['lijke', ''],
    ['ische', ''],
    ['heid', ''],
    ['lijk', ''],
    ['isch', ''],
    ['igen', ''],
    ['ing', ''],
    ['ige', ''],
    ['end', ''],
    ['en', ''],
    ['er', ''],
    ['te', ''],
    ['de', ''],
    ['es', ''],
    ['e', ''],
    ['s', ''],
  ],
  sv: [
    ['ningar', ''],
    ['ande', ''],
    ['ende', ''],
    ['ning', ''],
    ['het', ''],
    ['lig', ''],
    ['isk', ''],
    ['ast', ''],
    ['ade', ''],
    ['are', ''],
    ['igt', ''],
    ['ar', ''],
    ['er', ''],
    ['en', ''],
    ['et', ''],
    ['ad', ''],
    ['ig', ''],
    ['a', ''],
    ['e', ''],
  ],
};

/**
 * Compute a stem for grouping purposes.
 * @param {string} word - normalized (lowercase) word
 * @param {string} language - two-letter language code
 * @returns {string} stem key (may not be a real word)
 */
export function stem(word, language) {
  const rules = RULES[language];
  if (!rules) return word; // unsupported language → no grouping

  for (const [suffix, replacement] of rules) {
    if (word.endsWith(suffix)) {
      const base = word.slice(0, -suffix.length) + (replacement || '');
      if (base.length >= MIN_STEM) return base;
    }
  }
  return word;
}
